language: php
php:
    - 5.5
    - 5.4
    - hhvm

script: 
    - composer update --no-dev
    - cp -r app/content/Language/. vendor/anax/mvc/app/content/Language/
    - phpunit --bootstrap test/config.php test

notifications:
  email: false